project:
  type: website

website:
  title: "RNA Sequence Analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: example_1.qmd
        text: 'Example #1'
      - href: example_2.qmd
        text: 'Example #2'
      - href: example_3.qmd
        text: 'Example #3'
      - href: example_4.qmd
        text: 'Example #4'
      - href: example_5.qmd
        text: 'Example #5'
      - href: include_utils_1.qmd
        text: 'Utils'

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

